### ISSUE TITLE
#hook-specification priority comment needs update

### ISSUE THREAD

**Issue by meigo** [Elderjs/docs#10]
[elderguide.com/tech/elderjs/#hook-specification](https://elderguide.com/tech/elderjs/#hook-specification)

```js
priority: 50, // The priority level a hook should run at. Elder.js hooks run here 100 is the highest priority and 1 is the lowest priority.
```

**Comment by nickreese** [comment]
Because the docs are built from the code, I pushed v1.0.5 to update. Running build now. 

@meigo Thank you!
