### ISSUE TITLE
Svelte Summit video does not render correctly.

### ISSUE THREAD

**Issue by theafolayan** [Elderjs/docs#16]
The Svelte Summit video added in the last merged PR by the awesome @nickreese  does not render (to the best of my knowledge). 
I am opening a PR to fix this by providing the proper code, so the video displays as it should.

**Comment by theafolayan** [comment]
![image](https://user-images.githubusercontent.com/44205918/97918312-39db5300-1d56-11eb-8ad7-9bda95cdfe93.png)
This is a screenshot of what I'm talking about

**Comment by theafolayan** [comment]
![image](https://user-images.githubusercontent.com/44205918/97919507-2e892700-1d58-11eb-8b08-953eec4edfe4.png)

I have designed the following image to be used as a link to the actual video instead

**Comment by nickreese** [comment]
@theafolayan This should be working as expected now. Was a SSR/Hydration issue.
