### ISSUE TITLE
Typo in elderjs.md

### ISSUE THREAD

**Issue by egany** [Elderjs/docs#6]
> I use `nextjs` bug template for this one because I couldn't find any template in the repo. I hope this is acceptable.
> English is not my first language so I apologize for any mistake I make.

# Bug report

## Describe the bug

There are typos in some of the code snippets. `request` is misspelled as `requre`.

This happens in `elderguide.com/elderjs.md` at line 109 and 172. Example:

```js
// const externalData = await query.fetch(`https://yourdata.com/api/city/${requre.slug}`)
```

**Comment by nickreese** [comment]
@egany Fixed. :) Thank you
